# [START runtime]
runtime: nodejs12
service: default

handlers:
  # Routing for bundles to serve directly
  - url: /((?:runtime-es5|runtime-es2015|main-es5|main-es2015|polyfills-es5|polyfills-es2015|styles|runtime|main|polyfills|vendor|[0-9]+-es5|[0-9]+-es2015)\.[a-z0-9]+\.js)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/web-gos/\1
    upload: dist/web-gos/.*

  # Routing for bundle maps to serve directly
  - url: /((?:runtime-es5|runtime-es2015|main-es5|main-es2015|polyfills-es5|polyfills-es2015|styles|vendor)\.[a-z0-9]+\.js\.map)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/web-gos/\1
    upload: dist/web-gos/.*

  # Routing for a prod styles.bundle.css to serve directly
  - url: /(styles\.[a-z0-9]+\.css)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/web-gos/\1
    upload: dist/web-gos/.*

  # Routing for typedoc, assets, and favicon.ico to serve directly
  - url: /((?:assets|docs)/.*|favicon\.ico|apple-touch-icon\.png)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/web-gos/\1
    upload: dist/web-gos/.*

  # Routing for service worker files serve directly
  - url: /(manifest\.json|ngsw\.json|main-sw\.js|firebase-messaging-sw\.js|manifest\.webmanifest|ngsw-worker\.js|safety-worker\.js|worker-basic\.min\.js|ngsw_worker\.es6\.js\.map)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/web-gos/\1
    upload: dist/web-gos/.*


  #Default to English
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    static_files: dist/web-gos/index.html
    upload: dist/web-gos/index\.html
    http_headers:
      Strict-Transport-Security: max-age=31536000; includeSubDomains;
      Access-Control-Allow-Origin: lh-sint.appspot.com
