name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm install and build
        run: |
          npm install
          npm run build-prod --if-present
      - name: GCP Authenticate
        if: success()
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - name: Run deployment
        if: success()
        uses: actions/gcloud/cli@master
        with:
          entrypoint: gcloud
          args: app deploy ./app.yaml --quiet
