name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Google Cloud Platform (GCP) CLI - gcloud
        uses: actions-hub/gcloud@272.0.0
        with:
          # Project id
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          # GCP authorization credentials
          APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm install and build
        run: |
          npm install
          npm run build-prod --if-present
      - name: Run deployment
        if: success()
        uses: actions/gcloud/cli@master
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        with:
            entrypoint: gcloud
            args: app deploy ./app.yaml --quiet
