name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Publish app to Google App Engine
      uses: zxyle/publish-gae-action@2.1
      with:
          # The service account email which will be used for authentication.
          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL_GCP }}
          # The service account key which will be used for authentication.
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY_GCP }}
          # GAE project id
          project_id: ${{ secrets.GCP_PROJECT_ID }}
